apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-process-account
  labels:
    app: service-process-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-process-account
  template:
    metadata:
      labels:
        app: service-process-account
    spec:
      containers:
      - name: app-process-account
        image: polyglotxt/nodejs-aws-process-account:1
        env:
        - name: KAFKA_SERVER
          value: "3.133.60.253:9092"
        - name: DB_POSTGRES_USER
          value: "postgres"
        - name: DB_POSTGRES_PASSWORD
          value: "Polyglot#3000"
        - name: DB_POSTGRES_DATABASE_ACCOUNT
          value: "DB_ACCOUNT"
        - name: DB_POSTGRES_HOST
          value: "3.133.60.253"
        - name: DB_POSTGRES_ACCOUNT_PORT
          value: "5435"